Repository ChustaSoft/GamerPlatformUtils, pull requests merged in 2020-05, with the labels that each got.

#43 Improved ServiceCollection management and PlatformFactory
  ChustaSoft.GamersPlatformUtils.Abstractions/Base/PlatformBase.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatform.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Constants/OriginConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Contracts/IOriginBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Implementations/OriginBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Constants/SteamConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Contracts/ISteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/Constants/XboxConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/Contracts/IXboxBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/Implementations/XboxBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain/Implementations/PlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Services/Models/Information.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/PlatformMapper.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ServiceProviderBuilder.cs
Labels: enhancement

#45 Implemented Logger
  ChustaSoft.GamersPlatformUtils.Steam.Tests/ChustaSoft.GamersPlatformUtils.Steam.Tests.csproj
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/Base/TraceableViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ServiceConfigurationExtensions.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindowViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlViewModel.cs
Labels: maintenance, requirement

#46 Fixed parallelization trash files analysing
  ChustaSoft.GamersPlatformUtils.Services/Base/ServiceBase.cs
  ChustaSoft.GamersPlatformUtils.Services/ChustaSoft.GamersPlatformUtils.Services.csproj
  ChustaSoft.GamersPlatformUtils.Services/Implementations/AnalyzerService.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ServiceConfigurationExtensions.cs
Labels: bug

#50 Improved MainWindow style
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml
  ChustaSoft.GamersPlatformUtils.UI/Resources/chustasoft-logo.png
Labels: invalid

#52 Moved Cleaner implementation to infrastructure making it generic
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Repositories/IFileDeleteRepository.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Contracts/ISteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain/Implementations/PlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Infrastructure.Tests/ChustaSoft.GamersPlatformUtils.Infrastructure.Tests.csproj
  ChustaSoft.GamersPlatformUtils.Infrastructure.Tests/SystemFileRepositoryTests.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Implementations/SystemFileRepository.cs
  GamersPlatformUtils.sln
Labels: enhancement, invalid

#55 Improved Platforms ComboBox behaviour, integrating CommonNET WPF package
  ChustaSoft.GamersPlatformUtils.UI/Base/TraceableViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/Base/ViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/IViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/PlatformMapper.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/RelayCommand.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/VisibilityConverter.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindowViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Models/SelectablePlatform.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlViewModel.cs
Labels: bug, enhancement, requirement

#65 Connected Analysis service and Cleaner by the UI
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/CleanResult.cs
  ChustaSoft.GamersPlatformUtils.Services/Contracts/IFileService.cs
  ChustaSoft.GamersPlatformUtils.Services/Implementations/FileService.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Helpers/FileInfoMapper.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/PlatformMapper.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ServiceConfigurationExtensions.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlViewModel.cs
Labels: requirement

#67 Add secundary steam library
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Constants/SteamConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
Labels: requirement
