Repository ChustaSoft/GamerPlatformUtils, pull requests merged in 2020-04, with the labels that each got.

#17 Started UI implementation
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IAnalyzer.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/ICleaner.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/ILinkAssigner.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/ILinkFinder.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatform.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/CleanResult.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/GameLink.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/Information.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/Platform.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/ChustaSoft.GamersPlatformUtils.Domain.Origin.csproj
  ChustaSoft.GamersPlatformUtils.Domain.Steam/ChustaSoft.GamersPlatformUtils.Domain.Steam.csproj
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/ChustaSoft.GamersPlatformUtils.Domain.Xbox.csproj
  ChustaSoft.GamersPlatformUtils.Services/ChustaSoft.GamersPlatformUtils.Services.csproj
  ChustaSoft.GamersPlatformUtils.Services/Contracts/ILoadService.cs
  ChustaSoft.GamersPlatformUtils.Services/Implementations/InformationService.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/ChustaSoft.GamersPlatformUtils.Steam.Tests.csproj
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/AssemblyInfo.cs
  ChustaSoft.GamersPlatformUtils.UI/Base/ViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControl.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindowViewModel.cs
  GamersPlatformUtils.sln
  GamersPlatformUtils/ChustaSoft.GamersPlatformUtils.Domain.csproj
  GamersPlatformUtils/Implementations/PlatformFactory.cs
Labels: requirement

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  PULL_REQUEST_TEMPLATE.md
Labels: documentation

#24 Create PR Build for GitHub Actions
  .github/workflows/pr-build.yml
Labels: deploy, maintenance, requirement

#18 Implement origin business for ILinkFinder contract
  ChustaSoft.GamersPlatformUtils.Domain.Origin/ChustaSoft.GamersPlatformUtils.Domain.Origin.csproj
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Implementations/OriginBusiness.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Chustasoft.GamersPlatformUtils.Infrastructure.csproj
  Chustasoft.GamersPlatformUtils.Infrastructure/Contracts/IDirectoryRepository.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Contracts/IFileRepository.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Implementations/FileRepository.cs
  GamersPlatformUtils.sln
  GamersPlatformUtils/Implementations/PlatformFactory.cs
Labels: requirement

#22 Implemented botton Information functionality
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Constants/SteamConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Services/Contracts/ILoadService.cs
  ChustaSoft.GamersPlatformUtils.UI/Base/ViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Converters/InformationConverter.cs
  ChustaSoft.GamersPlatformUtils.UI/Converters/VisibilityConverter.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml
  ChustaSoft.GamersPlatformUtils.UI/MainWindowViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Resources/origin-logo.png
  ChustaSoft.GamersPlatformUtils.UI/Resources/steam-logo.png
  ChustaSoft.GamersPlatformUtils.UI/Resources/xbox-logo.png
Labels: requirement

#25 Add SteamAnalyzer
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IAnalyzer.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamAnalyzer.cs
Labels: requirement

#26 Declare IAnalyzer on IoC container
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
Labels: requirement

#27 Reorganized structure of business
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/ILinkFinder.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatform.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/PlatformBase.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Repositories/IDirectoryRepository.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Repositories/IFileRepository.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Constants/OriginConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Implementations/OriginBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Constants/SteamConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamAnalyzer.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Services/Models/Information.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Chustasoft.GamersPlatformUtils.Infrastructure.csproj
  Chustasoft.GamersPlatformUtils.Infrastructure/Contracts/IFileRepository.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Implementations/XMLFileRepository.cs
  GamersPlatformUtils/Implementations/PlatformFactory.cs
Labels: enhancement, maintenance, requirement

#28 Xbox business implementation
  ChustaSoft.GamersPlatformUtils.Abstractions/Repositories/IReadFileRepository.cs
  ChustaSoft.GamersPlatformUtils.Abstractions/Repositories/IReadWriteRepository.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Implementations/OriginBusiness.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/ChustaSoft.GamersPlatformUtils.Domain.Xbox.csproj
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/Constants/XboxConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Xbox/Implementations/XboxBusiness.cs
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Chustasoft.GamersPlatformUtils.Infrastructure.csproj
  Chustasoft.GamersPlatformUtils.Infrastructure/Implementations/PowershellRepository.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/Implementations/XMLFileRepository.cs
  Chustasoft.GamersPlatformUtils.Infrastructure/getInstalledMicrosoftAppsPs.txt
  GamersPlatformUtils/Implementations/PlatformFactory.cs
Labels: requirement

#34 Project templates changed an few enhancements
  .github/workflows/pr-build.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ChustaSoft.GamersPlatformUtils.Domain/ChustaSoft.GamersPlatformUtils.Domain.csproj
  ChustaSoft.GamersPlatformUtils.Domain/Implementations/PlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Services/ChustaSoft.GamersPlatformUtils.Services.csproj
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  GamersPlatformUtils.sln
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: deploy, documentation, enhancement, maintenance, requirement

#35 Fix stackOverflowException and Add test
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
Labels: bug

#38 Implemented Analyser funcionality on UI
  ChustaSoft.GamersPlatformUtils.Abstractions/Contracts/IPlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Domain/ChustaSoft.GamersPlatformUtils.Domain.csproj
  ChustaSoft.GamersPlatformUtils.Domain/Implementations/PlatformFactory.cs
  ChustaSoft.GamersPlatformUtils.Services/Contracts/IAnalyzerService.cs
  ChustaSoft.GamersPlatformUtils.Services/Implementations/AnalyzerService.cs
  ChustaSoft.GamersPlatformUtils.Services/Implementations/InformationService.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/ChustaSoft.GamersPlatformUtils.Steam.Tests.csproj
  ChustaSoft.GamersPlatformUtils.UI/App.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/Base/ViewModelBase.cs
  ChustaSoft.GamersPlatformUtils.UI/ChustaSoft.GamersPlatformUtils.UI.csproj
  ChustaSoft.GamersPlatformUtils.UI/Contracts/ILoadable.cs
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Controls/InformationControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Converters/InformationConverter.cs
  ChustaSoft.GamersPlatformUtils.UI/Enums/ViewModelType.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/IViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/PlatformMapper.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/RelayCommand.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/ViewModelFactory.cs
  ChustaSoft.GamersPlatformUtils.UI/Helpers/VisibilityConverter.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml
  ChustaSoft.GamersPlatformUtils.UI/MainWindow.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/MainWindowViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Models/SelectablePlatform.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControl.xaml
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControl.xaml.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Modules/Cleaner/CleanerControlViewModel.cs
  ChustaSoft.GamersPlatformUtils.UI/Styles/StyleConstants.cs
Labels: requirement

#40 Implemented IAnalyzer on Origin business
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Constants/OriginConstants.cs
  ChustaSoft.GamersPlatformUtils.Domain.Origin/Implementations/OriginBusiness.cs
Labels: requirement

#41 Implement Cleaner for Steam
  ChustaSoft.GamersPlatformUtils.Abstractions/Models/CleanResult.cs
  ChustaSoft.GamersPlatformUtils.Domain.Steam/Implementations/SteamBusiness.cs
  ChustaSoft.GamersPlatformUtils.Steam.Tests/SteamBusinessTests.cs
Labels: requirement
